docker stop mongos0
docker rm mongos0
docker stop configsvr0
docker rm configsvr0
docker stop configsvr1
docker rm configsvr1
docker stop configsvr2
docker rm configsvr2
docker stop shardsvr00
docker rm shardsvr00
docker stop shardsvr01
docker rm shardsvr01
docker stop shardsvr02
docker rm shardsvr02
docker stop shardsvr10
docker rm shardsvr10
docker stop shardsvr11
docker rm shardsvr11
docker stop shardsvr12
docker rm shardsvr12

